### ISSUE TITLE
No remote address or port for UDP

### ISSUE THREAD

**Issue by JulienTant** [pytimer/win-netstat#1]
Hello,

Is there any plan to implement remote addr & port for UDP protocol?

**Comment by pytimer** [comment]
Sorry, i was on holiday before.

I am not good at Windows, so i don't know how UDP protocol get remote address and port with windows dll. But i will try to look up the answer about it. 

If you have some idea, hope you can tell me. Or you can send PR to implement it.

**Comment by JulienTant** [comment]
Hello,

No worries, it's so awesome to have this open-sourced ! 

Let me be honest, I would love to contribute but i've no idea how all those networks things works :(.

The only thing i found is that the ports are into UDP headers, so maybe it requires to "listen" to the network to get the informations ? https://en.wikipedia.org/wiki/User_Datagram_Protocol#Packet_structure

This is also all i found online : https://microsoft.public.win32.programmer.networks.narkive.com/Q6uMxCvG/getudptable-endpoints#post2
